### ISSUE TITLE
如何配置文件映射用于更新cookies

### ISSUE THREAD

**Issue by mumumi** [zhangfangbiao/docker#1]
rt

**Comment by zhangfangbiao** [comment]
> rt

我是用的docker，编辑docker-compose.yml，如果多账号使用&连接
![image](https://user-images.githubusercontent.com/49065946/123611911-a7cc1180-d834-11eb-9ad9-26a473ab812c.png)

**Comment by mumumi** [comment]
现在我把参数提到.env，单独更新.env就行
